version: 2
updates:
  # npm packages in the vuln-api
  - package-ecosystem: "npm"
    directory: "/infra/vuln-api"
    schedule:
      interval: "monthly"
      open-pull-requests-limit: 3
    labels:
      - "dependencies"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "ci"
